þZUUZþWUWWWWWZþUXXWUXUX[WWUþUWZUXUXWWXZU[WZZþVUW[WVZó[Z[ZWWWZþ
ZZWZZZXóôZZXWXWZUZUþZZZZVWUWðôöôôö÷ZXZUWUZZWþWZZVZWUWWZðóùóòóô÷øZWWUWZVZZWþWZZUWUZðõúôø÷ø÷ôôõú÷UWVZZZZþUZUZWùøûõùùùúõ÷ùûøZWZZþ
ZWWWZöúùúüúùø
ûWUVþZZW[XUXWWûúùWUþUWW[UXXUWXXUþZWWWWWUWþZUUZÿþöùþø	ùþø	øþþøô÷þóóó	þôôöþZ
ô÷þóóóó	þ	÷ô	öþøþø÷ùù	ô	
óóóþ÷ô	öUùùùø
	óþö÷ô	ö÷			ùø÷øþ
ôù÷ô	øôô

ùöö÷÷þ
	
÷÷÷ôö÷ø	ôôöø÷÷ùþZóó	÷ööôôô÷ù÷ö÷÷ô	ùööøùöþWZZ
øùù÷	òòùøøù
øùöøööVZZWþWZZUWUøôø
òòôöôó
øöùùøZZþUZUZWXWùöôùóóóó	õWZZþ
ZWWWZ\ôù	óöñóùWUVþZZXZöù
óóóöùWUþUùùùùøøøùXXUþZWWWWWUWþZUUZÿþZUUZþWUWWWWWZþUXXWUôôõ[WWUþUWZUòòöWZZþVUW[òòWWWZþ
ZZWZZ²³óõZUZUþZZZZVôó´³²²ôóòø÷UZZWþWZZVZWU	÷õóò´µ´´òôõôóùúùWZVZZWþWZZUW	ùöôõóµ·¶··óöúùûZZZZþUZUZú÷÷øöù¹¸¶¶øùüúùWZZþ
ZWWùùúõøúö¹¹øùúüûUVþZZW[Xú÷ø¹ùúûZWUþUWW[			UþZWWWWWUWþZUUZÿþõóóóóóóóóóóóóþõôóôôôôôôõõôôôôþôôóóôôôõõ÷óôôôôôþõôõõóóôôôóóôôôôôôôþôõõóóôôôôõõõóóôôôþõô
õõóóôôôõøóóôôôôôþôõ

õõôóôôôóóôôôõôôôþ	õôõõ	õóôóôôôôôõõ÷óôôôþõõõ	
õõöööööööõõõöööþôõõõõõ
ööõööþõôõõõõõ	ö÷÷÷÷÷÷÷÷÷öþô

õõõõö÷ö÷÷÷÷÷÷öþõôõõõõ÷ö÷÷÷÷÷ø÷öþôõõõ		õööö÷øö÷øùøöþôõõõ
õ	ö÷÷ø÷øùùùöþõ	õõõõõ
õö÷÷ùøù÷ùZZ[öþò
õõõõõõöøùù÷ùùøXXZ[þZZZZõ
õõõõöø÷ZøZøù[XVXZZWþWZZVZWUõ	VXõöZZXZV[ZZWUWZVZZWþWZZUWUXVUõööZVWVXXZWUWVZZZZþUZUZWXUVUöZXWXZZWXZZZWZZþ
ZWWWVVVXXZZXXZVW[WUVþZZWVXUXWWXUXUZWUþUWW[UXXUWXXUþZWWWWWUWþZUUZÿþµ¢£[þ[£¢¡]][£¡£Y£þ£¡£[]]£££\[][]Yþ^][[ZY£¡[¡¢\\ZZ[¢þ£YZZZ£¡¡¡££[[ZYµ£^þY]][ZYYYYY[[[Z£¢^]]þ^¢[Z¢£[ZZZ[Z¢µ¡Y[\\þ^£µ£¡µ¢Z[¡¢Y\^\[[[þ]\][][£µµ]]\[Z[[[\þ\[[£¢¡[]]£ZZ¢Z[[[[þ[[Z££¡¢Y¢YZZ£Z[[[Zþ\[ZY£¡¢£¢£YZZYZ[¢Z]þ[[ZY£¡¡££¡££YYZY\^]þZZZ[¢Y¢££¡£Y£¢¢[[\\þ]£µ¢µ¡¢££¡¢Y\^^[[[þV]]Z[]Y¡µµ]]\[Z[[[\Zþ
ZZW\[[YYZ[]]ZZZZZ[[[ZUZUþZZZZV[[Z£££¢YZYZZXWX[ZUWUZZWþWZZVZWU\[Z£££¡£££YXWUWXXWUWZVZZWþWZZUWU[ZY££¡£££WSUSUWUWVZZZZþUZUZWWZYY£¢YXWUTSUWWZWZZþ
ZWWWZYXWWWWUWUUWUWUVþZZW[XUXYWWUWWUWUþUWW[UXXUWXXUþZWWWWWUWþZUUZÿþþ
þ

yþ			
y
þ

	
	
þ		
			
þ
	

	
;þ
		


þ

ö	
÷<=þ




÷øù=þøùùþ
þ
	
þ
		

þ

ö	
þ	




þ

þVU		Zþ
ZZWZ
	UZUþZZZZVW
		

WUZZWþWZZVZWUW

ö	
UWZVZZWþWZZUWUZ




WVZZZZþUZUZWYZ[ZWZZþ
ZWWWY[[WUVþZZW[WUþUWW[XXUþZWWWWWUWþZUUZÿþþüþüþüü
üþüW
üüUþüXUXüüWZZþVüüZZZ
üüZWWWZþ
[ZWüü[\[	üüWXWZUZUþZZZZVWUZü\\\	üXZXZUWUZZWþWZZVZWUWWXüü]^^
XW[ZWWUWZVZZWþWZZUWUZð\\\\XZXZ[UWVZZZZþUZUZW[[\Z[ùZ[\[ZZZWZZþ
ZWWWZZZZZ[\ZZ\\WUVþZZW[XUXWWZZ\WUþUWW[UXXUWXXUþZWWWWWUWþZUUZÿþþ
þ
þ	

þ

úú
þ
		
ü
þ
		

ü
þ

óñññ	
üüþ





üüþ	üüüþ

üüüþ
	þüüüüüüþ
		

üü
üüþ	


óñññ	
ü
üþ







ü
ü
þ

üüüþ
óüüü
þüüþ
óüüüüü
þüþ
	üü

üü
üþüþñ




üþüþñ

ó
	
üþüþñ
ó
üüüþüþ
	
üüüþ	ü
ñüüüüþ
ü
ñüü
üþùü
ñü	
üþü
üüüþ

üü	üüüþWZZüüü
üüüZWþWZZüüüüüüüùüüüZZþUZUZ
üüüüZZþ
ZWWüüü

WUVþZZWüüüüüWUþUWW[UXXUWXXUþZWWWWWUWþZUUZÿþ]VVXþ[V[XX[[VþV]\ZZZ[]]]]XþV[Z[\\\\]]]][WX[þWV[Z\\]]]]]^]]\[]]XWþ
]]X][\]]]]]^^^^]]]\\ZZVXþZZ][[[]]]^^^^^^^^^^]][ZX[[]§þX]]WZ[[\]]^________^^]]\ZZ\\]]]]þ[ZZV[[]^^_______^^^]]\[[ZZWXþV]VZ\]^_____^]]]]]\[ZZXVþ
]X\\]]^^^^]]\\\[\ZZXþ]Z[\]]]]\[ZZYZYXþV[]]\[ZZXXXYþ]][YV\[Xþ]VVXÿþZUUZþWUWWWWWZþUXXWUXUX[WWUþUWZUXUXWWXZU[WZZþVUW[WVZXZZZX[Z[ZWWWZþ
[]WZZZXWZYWUWZZZXWXWZUZUþ[ZZZVWUWWYZXWWZWYZUZXZUWUYZWþWZZVXWUWWZVUWYUZXUXWZVZWWUWZVZYWWVWZZUWUZXVXZZWXWWXZZWWUWVYZZYVVTWZZUZUZWXWXZZZZWZZZWXZZZWZZWVVVVW]WWUZWWWY[Y[XYZXXZVW[WUVZXWWY[UUT]WWVVZZW[XUXWWXUXUZWUZZZZ[[[]VVU[[YYXTUUWW[UXXUWXXUX\\\[YYY[WWXVVVTWZZWWWZWWWWWUWZZ\\\[ZXYW[[W[YYVVYZZU]YWUZUUZZZ[[\\[WSXVV[[UWWTVVZT[VYYY\XXZZ[[\\[\X\VV[[YZþUWWTVVZZ[VYY[W[[VWXX][\Z[[ZZþWW\]Z[ZV[VXW[\WWX\[\\\ZZþ
UTZWXWVUZYV[YX[[\\\XþVVWWZVUUV[[[ZZZZþUWWWWVXYWWXZþWVWTVVVWþVWVVÿþZUUZþWUWWWWWZþUXXWUXUX[WWUþUWZUXUXWWXZU[WZZþVUW[WVZXZZZX[Z[ZWWWZþ
[]WZZZXWZYWUWZZZXWXWZUZUþ[ZZZVWUWWYZXWWZWYZUZXZUWUYZWþWZZVXWUWWZVUWYUZXUXWZVZWWUWZVZYW[VWZZUWUZXVXZZWXWWXZZWWUWVYZZYZZ\W[\UZUZWXWXZZZZWZZZWXZZZWZZWZZZ\\W][[ZWWWY[Y[XYZXXZVW[WUVZX]\^XU\TTW\Y^ZZW[XUXWWXUXUZWUZZZZ[[[VVV\WWXWXTUUWW[UXXUWXXU[]]\[[]V[VW[^]\]XZZVWWZWWWWWUWZZ]X^[Y]VW[[[[Y\^^\]VVTWW\ZUUZZZ[[\]W\]VVZZ\\\\[[UW\WVTWWYYY\[\[\VZWY[VVZ[]\XUU\UYX\ZVTUWWWYZZWZVZ\]Y^XZZ\\\]V\\U[\[\TTTUYUY\ZV^Z\YWVY][Z\\[WXUUU[\W]TTUTY[[VVZ^\]Y]Y[^]]\\Z[XZT]\Z\\TUYYU\]UW]]]V\TW\]]]\XYWXXU\WV[[YUU[ZUUY[]V[TY\\Y\]VXXXWXT\X[U[\]\\UU[[XY^^WX^\Y[V]XXYTZT[\[[Y^]UZUXYZ[\UYY]\\^]Y^XYXTT]]T[[\XTTT]ZXWXVUX]XYWYYVY\ZWX[Y[TY[]YW]\Y\^YY[VY[]\[YVWZY[ZY[[TTTU\[YY][[YWXYXVV][[Y[WW^\U[[^ZTVTTWWX[U[UXXWYYVV[YVVXW\Z[\UUY^TTTU\[]XY]TZXZYXVV]VWVX\^Y[^WWX\\YYXX\]XY\U]\W\\XV]\WW[YWZZW\^YXWWTTTW\YXUT[VW[ZWV]ZXW[^ZW[Y]YYWWYYT[U^Y\X\[UXX[^ZZXVWTXVWZ\[^YVWWVT\UZUY]\[\\X[VVVXY]\\\\[[[\þUWWTV[\TYVYX[W[WVV^X\[û\[[ZZþ]^V\[W\VVVX][WW]XY]\\\ZZþ
UTZWWW[YVVVXYY[\\\\XþVV[WTTUUV[[[ZZZZþUWWWWVXYWWXZþWVWTVVVWþVWVVÿ	þZUUZþWUWWWWWZþUXXWUXUX[WWUþUWZUXUXWWXZU[WZZþVUW[WVZXZZZX[Z[ZWWWZþ
[]WZZZXWZYWUWZZZXWXWZUZUþ[ZZZVWUWWYZXWWZWYZUZXZUWUYZWþWZZVXWUWWZVUWYUZXUXWZVZWWUWZVZYWWVWZZUWUZXVXZZWXWWXZZWWUWVYZZYVVTWVWUZUZWXWXZZZZWZZZWXZZZWZZWVVVVW]W\\ZWWWY[Y[XYZXXZVW[WUVZY]WYXUUTTWWV[ZZW[XUXWWXUXUZWUZ]Y[[[[VVV[WWX]\T\UWW[UXXUWXXUX\\\W\YY[VWXVVVTW\ZV[[ZWWWWWUWZZ\[\YY\YW[[W[YYVVT\V[T[\]ZUUZZZ[Y^^WXXXY[[]UV\YWU[Z\[[Y^]VYWZZW[\X\Y\\Z^]Y^XWZTT]]VUT\XTZX]YY[XVY\\XYWZ[[YYXZZ[Y[WUV]YV]\Y\^XZ[\Y\XW[WZ[UY[XZ[[TTXV\[VU][[YYYW]\XVXXV[Z[^\UYX^TTUTTWUXTT[XZYX]Y]\WVXZZW\\W\XXY^VTTT\[]UU]XWZZX]]\WWXZWZZ\W^YXW\\YYXX\]UY\V]\Z\\[ZYWVZ[Y[Y[WYWWYWTTUUW\Y\UU[X[[ZZXVZVX[WZYYYYVWWVTYU[U^Y\\\[V]XV^XY\\WT\[\[\þUWWTVV\TVVY]\[\\X[XX\[\][[ZZþ[þWWVZZ[\VYVXW[[WWXY^\\[ZZþ
]^Z\[W\UVVV]YW[]\\]XþVVWWWT[YV[[XZZZZþUW[WWVXYWWXZþWVWTVVVWþVWVVÿþZUUZþWUWWWWWZþUXXWUXUX[WWUþUWZUXUXWWXZU[WZZþVUW[WVZXZZZX[Z[ZWWWZþ
[]WZZZXWZYWUWZZZXWXWZUZUþ[ZZZVWUWWYZXWWZWYZUZXZUWUYZWþWZZVXWUWWZVUWYUZXUXWZVZWWUWZVZYWWYWZZUWUZXVXZZWXWWXZZWWUWVYZZYZ]VXYWUZUZWXWXZZZZWZZZWXZZZWZZZ]]]ZXW[WYZWWWY[Y[XYZXXZVW[WUVZ\Z]Y\YUWVXWZYZZW[XUXWWXUXUZWUZ]]]^]^ZZYYWW\XZVYUWW[UXXUWXXUW^^\^]Y\^ZX[ZZZWW]ZYXZZWWWWWUWZ]^]^^Y[YZ]^W\\YZZW]YYVTXYZUUZ]Z^^]^^^^YUZ\^YY^\ZYU]ZYWWWYY\\^\^^\^]\]\YZ^_YZUW\YYVZ]YWYWTZ]]]ZYYYXYY^®^]]]\ZYYWXYY]ZWVW[\Y\Y_]_]ZYU\\_^]ZZ^ZWYXWVZZWVVWVVY\ZZ^]\YZ^_®___Y]]]ZZUWY]YWVYVWYY\ZZ]ZYX_®®®^^__[YTZW]YVWVVVVYUY]WY\^Y]®®®[]__^Z\\\Z\\YZVWYYYYXZ][^]YX]^]^^^^__ZZ\Y\ZW][WWVZTWY]Z\Y]^\]]\^]_\]^\ZY\]]WYX\VZWVWVZ]\Z]ZZ\Y^_Z^]]_\Z[YZZVW\YYVWVWV]Y\Y\^ZZ[]^YZYZ_YZ\[]]WVUZVWVWVW[Z\\Y[]\^_]YZZ]®ZZ^ZZVYWVWWZZYUYWZ\^^^Z^_\^YZ]_^YUY\\WVVYVV[]Y]V]Z]]X__[^[YZZ]_^^[Z\ZYWZWWVX[[^YUZW]]Y_[^ZY[]^_Z^ZZ\Z[WWVVW]Z[[YYYZ^]Z]^ZYUZ]^Z^Y^\YZZYZWVY^[W[_UYZY]Z]Z[Z]ZYZ[]\\Y\Z[[YVWUY^^]Z_YYY_^ZZ\Y^]___^\^^þYWXWYY]W]^[Y^W^]ZZ[\^__®_^]]þWWY]ZXZ]_ZYW\^W\Y]^_®_Z]þ
YW]W[\^YYZZ^\\^^^®]ZþYZXWWVYYZ]^\]]]ZþYTZXTZ\YZZ\ZþXYWWYYZZþYWYYÿþZUUZþWUWWWWWZþUXXWUXUX[WWUþUWZUXUXWWXZU[WZZþVUW[WVZXZZZX[Z[ZWWWZþ
[]WZZZXWZYWUWZZZXWXWZUZUþ[ZZZVWUWWYZXWWZWYZUZXZUWUYZWþWZZVXWUWWZVUWYUZXUXWZVZWWUWZVZYWYVWZZUWUZXVXZZWXWWXZZWWUWVYZZYZZZWYZUZUZWXWXZZZZWZZZWXZZZWZZWZZZZZW[YYZWWWY[Y[XYZXXZVW[WUVZX]\\XUZTTWZX\ZZW[XUXWWXUXUZWUZZZZ[[[VVVZWWXWWTUUWW[UXXUWXXUY[[\[[]V[VWY\[Z[WZZZWWZWWWWWUWZZ[W^[Y]VW[[Y[YZ\\Z[VVZWWZZUUZZZ[[\[V\]VTZZ\ZZ\YYUUZWVSZWXXY\[\[\VZVYYVTZ[]\XUU\UXWZZVSUWWWYZZWZVZ\[Y\XZZ\\\[VZZUWZYZTRTUYUYZZV\Z\YUVX[[Z\\[WXUUUYZW[VTUTYYYVVZ^\]X[XY^]]\\ZYXZT[ZZZZWVYYUZ[UW][]VZTVZ]]]\XYWXXUXZWVYYYUUYZUVY[]VYTX\ZX\]VXXXWXTXZXYUYZ[ZZUW[[XX\\VW^\XYV[XXYTZTYXZYYX\[UZWXYZYZUYX]\\\[X\XYXST[[T[[ZWVTV[ZXWWWUX]WXWYYVX\ZWXYXYTY[[XW[ZXZ\YYZVY[]\YYVWZX[ZYYYXWSUZYZY[ZYXWXYXUW][[YYWW\ZU[[\ZVVRTVWZ[UYWXXWYXVW[YVUXVZZ[ZUUY\WVTUZY[ZY[VZX[ZXWV]VWVX\^Y[\WW\ZZXXWWZ[XXZU[ZW[ZXW]\WWYXWZZVZ\YXWWTTTVZXXUTYVWY[WW]ZXWY^ZW[Y[YYWWYXTYT\XZXZYUXW[\ZZXVVTXVXZZY\YVWWVTZUZUX[ZYZZWYZVTXY[\^\\[Y[\þUWWTVYZTXVYX[W[VVT\X\Y^\[[ZZþ[\VZYWZVVVX[[VW[XY[^\\ZZþ
UTZWUWYXVVVWYY[\^\\XþVVYUTTUUV[[[ZZZZþUWWWWVXYWWXZþWVWTVVVWþVWVVÿþZYUZþWUWWWWWZþUXXWUXUY[WWUþUWZUXUXWTXZU[WZ\þVUW[WVZXXWUX[Z[ZWWYZþ
[]WZZZXW\YWUWYZ\XWXYZUZUþ\[Z\VWUWWYZXWWZWYZUZXZUTXYZXþW[ZVXWUWWZVUWYUZXUXWZVZWZUWZVWYWWYWZZUWUZXVXZZWXVWX[ZW[Z[VYVXYZ]VXYWUZUZWXWX[\ZZWZYZWX\]ZWXYZ]]]ZXW[WYZWWWY[Y[XYZYXYVW[WUVZ\Z]Y\YUWVXWZYZZW[XUXWWXUXUZWUZ]]Z^]^ZZYYWW\XZVYUWW[UXXUWXXUW^^\Y_[_^ZX[ZZZWW]ZYXZZWWWWWUWZ]^]^^Z]^_]^W\\YZZW]YYVTXYZUUZ]Z^\]^\^]]^®\^YY^\ZYU]ZYWWWYY\\^\^\[^]\]^ZY\_YZUW\YYVZ]YWYWTZ]]]ZXZXYZ]^ZVX^]\ZYXWXYY]ZWVW[\Y_\_]ZZY\]^\ZW[YZ^ZWYXWVZZWVUWVVY\[\\WYZ]_]Z\Y]^]]][[UWY]YWUTVWYY\Z[YYXYYZ[[^XZ_[YT\W]YXWVUVVYUY]WY\^Y][ZZ[][Z^Z\\\Z\\YZVWYYYYXZ][^]YX]^]^^^^[_ZZ\Y\ZW][XWVZTWY]Z\Y]^\]]\^]_\]^\ZY\]]WYX\VZWVWVZ]\Z]ZZ\Y^_Z^]]_\Z[YZZVW\YYVUSUV]Y\Y\^ZZ[]^YZYZ_YZ\[]]WVUZVWVUVW[Z\\Y[]\^_]WYZ]\ZZ^ZZVYWVWWZZWUYWZ\^^^Z^_\^YZ]_\YWY\\WVVYVV[]Y]V]Z]]X__[^[YZZ]_^\[Z\ZYWZWWVX[[^YUZW]]Y_[^ZY[]^_Z^ZZ\Z[WWVVW]Z[[YYYZ^]Z]^ZYZZ]^Z^Y^\YZZYZWVY^[W[_UYZY]Z]Z[Z]ZYZ[]\\Y\Z[[YVWUY^^]Z_YYY_^ZZ\Y^]___^\^^þYWXWYY]W]^[Y^W^]ZZ[\^__®_^]]þWWY]ZXZ]_ZYW\^W\Y]^_®_Z]þ
YW]W[\^YYZZ^\\^^^®]ZþYZXWWVYYZ]^\]]]ZþYTZXTZ\YZZ\ZþXYWWYYZZþYWYYÿ